# 開発時はdocker-compose.ymlからビルドすること

FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
RUN pip install --no-cache-dir -r requirements.dev.txt

CMD ["tail", "-f", "/dev/null"]
