FROM python:3.12-slim

ARG NOTION_TOKEN
ARG TASK_DB_ID
ARG TEST_VAR

ENV NOTION_TOKEN=${NOTION_TOKEN}
ENV TASK_DB_ID=${TASK_DB_ID}
ENV TEST_VAR=${TEST_VAR}

WORKDIR /app
COPY . .
RUN rm -rf build dist *.egg-info notiontaskr/*.egg-info
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "notiontaskr/daily_job.py"]

