FROM python:3.12-slim

# ARG NOTION_TOKEN
# ENV NOTION_TOKEN=$NOTION_TOKEN
 
WORKDIR /app
COPY . .
RUN rm -rf build dist *.egg-info src/*.egg-info
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "src/job.py"]

