FROM python:3.12-slim

# ARG NOTION_TOKEN
# ENV NOTION_TOKEN=$NOTION_TOKEN
 
WORKDIR /app
COPY . .
RUN rm -rf build dist *.egg-info src/notiontaskr/*.egg-info
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements.dev.txt

# テスト実行のコマンドに変更
CMD ["pytest", "--maxfail=1", "--disable-warnings", "-q"]
