FROM python:3.12-slim

ARG NOTION_TOKEN
ENV NOTION_TOKEN=$NOTION_TOKEN
 
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
RUN pip install --no-cache-dir .
CMD ["gunicorn", "app.main:app", "--bind", "0.0.0.0:$PORT", "--workers", "2", "--threads", "4"]

